// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: schema.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Weekday int32

const (
	Weekday_SUNDAY    Weekday = 0
	Weekday_MONDAY    Weekday = 1
	Weekday_TUESDAY   Weekday = 2
	Weekday_WEDNESDAY Weekday = 3
	Weekday_THURSDAY  Weekday = 4
	Weekday_FRIDAY    Weekday = 5
	Weekday_SATURDAY  Weekday = 6
)

// Enum value maps for Weekday.
var (
	Weekday_name = map[int32]string{
		0: "SUNDAY",
		1: "MONDAY",
		2: "TUESDAY",
		3: "WEDNESDAY",
		4: "THURSDAY",
		5: "FRIDAY",
		6: "SATURDAY",
	}
	Weekday_value = map[string]int32{
		"SUNDAY":    0,
		"MONDAY":    1,
		"TUESDAY":   2,
		"WEDNESDAY": 3,
		"THURSDAY":  4,
		"FRIDAY":    5,
		"SATURDAY":  6,
	}
)

func (x Weekday) Enum() *Weekday {
	p := new(Weekday)
	*p = x
	return p
}

func (x Weekday) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Weekday) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[0].Descriptor()
}

func (Weekday) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[0]
}

func (x Weekday) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Data struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Facilities  *[]*Facility           `protobuf:"bytes,1,rep,name=facilities"`
	xxx_hidden_Attribution []string               `protobuf:"bytes,2,rep,name=attribution"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Data) GetFacilities() []*Facility {
	if x != nil {
		if x.xxx_hidden_Facilities != nil {
			return *x.xxx_hidden_Facilities
		}
	}
	return nil
}

func (x *Data) GetAttribution() []string {
	if x != nil {
		return x.xxx_hidden_Attribution
	}
	return nil
}

func (x *Data) SetFacilities(v []*Facility) {
	x.xxx_hidden_Facilities = &v
}

func (x *Data) SetAttribution(v []string) {
	x.xxx_hidden_Attribution = v
}

type Data_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Facilities  []*Facility
	Attribution []string
}

func (b0 Data_builder) Build() *Data {
	m0 := &Data{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Facilities = &b.Facilities
	x.xxx_hidden_Attribution = b.Attribution
	return m0
}

type Facility struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name              string                 `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Description       string                 `protobuf:"bytes,2,opt,name=description,json=desc"`
	xxx_hidden_Source            *Source                `protobuf:"bytes,3,opt,name=source"`
	xxx_hidden_Address           string                 `protobuf:"bytes,4,opt,name=address"`
	xxx_hidden_XLnglat           *LngLat                `protobuf:"bytes,5,opt,name=_lnglat"`
	xxx_hidden_NotificationsHtml string                 `protobuf:"bytes,6,opt,name=notifications_html,json=notificationsHtml"`
	xxx_hidden_SpecialHoursHtml  string                 `protobuf:"bytes,7,opt,name=special_hours_html,json=specialHoursHtml"`
	xxx_hidden_ScheduleGroups    *[]*ScheduleGroup      `protobuf:"bytes,8,rep,name=schedule_groups,json=scheduleGroups"`
	xxx_hidden_XErrors           []string               `protobuf:"bytes,9,rep,name=_errors"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Facility) Reset() {
	*x = Facility{}
	mi := &file_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facility) ProtoMessage() {}

func (x *Facility) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Facility) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Facility) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *Facility) GetSource() *Source {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return nil
}

func (x *Facility) GetAddress() string {
	if x != nil {
		return x.xxx_hidden_Address
	}
	return ""
}

func (x *Facility) GetXLnglat() *LngLat {
	if x != nil {
		return x.xxx_hidden_XLnglat
	}
	return nil
}

func (x *Facility) GetNotificationsHtml() string {
	if x != nil {
		return x.xxx_hidden_NotificationsHtml
	}
	return ""
}

func (x *Facility) GetSpecialHoursHtml() string {
	if x != nil {
		return x.xxx_hidden_SpecialHoursHtml
	}
	return ""
}

func (x *Facility) GetScheduleGroups() []*ScheduleGroup {
	if x != nil {
		if x.xxx_hidden_ScheduleGroups != nil {
			return *x.xxx_hidden_ScheduleGroups
		}
	}
	return nil
}

func (x *Facility) GetXErrors() []string {
	if x != nil {
		return x.xxx_hidden_XErrors
	}
	return nil
}

func (x *Facility) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Facility) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *Facility) SetSource(v *Source) {
	x.xxx_hidden_Source = v
}

func (x *Facility) SetAddress(v string) {
	x.xxx_hidden_Address = v
}

func (x *Facility) SetXLnglat(v *LngLat) {
	x.xxx_hidden_XLnglat = v
}

func (x *Facility) SetNotificationsHtml(v string) {
	x.xxx_hidden_NotificationsHtml = v
}

func (x *Facility) SetSpecialHoursHtml(v string) {
	x.xxx_hidden_SpecialHoursHtml = v
}

func (x *Facility) SetScheduleGroups(v []*ScheduleGroup) {
	x.xxx_hidden_ScheduleGroups = &v
}

func (x *Facility) SetXErrors(v []string) {
	x.xxx_hidden_XErrors = v
}

func (x *Facility) HasSource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Source != nil
}

func (x *Facility) HasXLnglat() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_XLnglat != nil
}

func (x *Facility) ClearSource() {
	x.xxx_hidden_Source = nil
}

func (x *Facility) ClearXLnglat() {
	x.xxx_hidden_XLnglat = nil
}

type Facility_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name              string
	Description       string
	Source            *Source
	Address           string
	XLnglat           *LngLat
	NotificationsHtml string
	SpecialHoursHtml  string
	ScheduleGroups    []*ScheduleGroup
	XErrors           []string
}

func (b0 Facility_builder) Build() *Facility {
	m0 := &Facility{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Source = b.Source
	x.xxx_hidden_Address = b.Address
	x.xxx_hidden_XLnglat = b.XLnglat
	x.xxx_hidden_NotificationsHtml = b.NotificationsHtml
	x.xxx_hidden_SpecialHoursHtml = b.SpecialHoursHtml
	x.xxx_hidden_ScheduleGroups = &b.ScheduleGroups
	x.xxx_hidden_XErrors = b.XErrors
	return m0
}

type Source struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Url   string                 `protobuf:"bytes,1,opt,name=url"`
	xxx_hidden_XDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=_date"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Source) GetUrl() string {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return ""
}

func (x *Source) GetXDate() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_XDate
	}
	return nil
}

func (x *Source) SetUrl(v string) {
	x.xxx_hidden_Url = v
}

func (x *Source) SetXDate(v *timestamppb.Timestamp) {
	x.xxx_hidden_XDate = v
}

func (x *Source) HasXDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_XDate != nil
}

func (x *Source) ClearXDate() {
	x.xxx_hidden_XDate = nil
}

type Source_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Url   string
	XDate *timestamppb.Timestamp
}

func (b0 Source_builder) Build() *Source {
	m0 := &Source{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Url = b.Url
	x.xxx_hidden_XDate = b.XDate
	return m0
}

type LngLat struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Lng float32                `protobuf:"fixed32,1,opt,name=lng"`
	xxx_hidden_Lat float32                `protobuf:"fixed32,2,opt,name=lat"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LngLat) Reset() {
	*x = LngLat{}
	mi := &file_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LngLat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LngLat) ProtoMessage() {}

func (x *LngLat) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LngLat) GetLng() float32 {
	if x != nil {
		return x.xxx_hidden_Lng
	}
	return 0
}

func (x *LngLat) GetLat() float32 {
	if x != nil {
		return x.xxx_hidden_Lat
	}
	return 0
}

func (x *LngLat) SetLng(v float32) {
	x.xxx_hidden_Lng = v
}

func (x *LngLat) SetLat(v float32) {
	x.xxx_hidden_Lat = v
}

type LngLat_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Lng float32
	Lat float32
}

func (b0 LngLat_builder) Build() *LngLat {
	m0 := &LngLat{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Lng = b.Lng
	x.xxx_hidden_Lat = b.Lat
	return m0
}

type ScheduleGroup struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Label               string                 `protobuf:"bytes,1,opt,name=label"`
	xxx_hidden_XTitle              string                 `protobuf:"bytes,2,opt,name=_title"`
	xxx_hidden_ScheduleChangesHtml string                 `protobuf:"bytes,3,opt,name=schedule_changes_html,json=scheduleChangesHtml"`
	xxx_hidden_Schedules           *[]*Schedule           `protobuf:"bytes,4,rep,name=schedules"`
	xxx_hidden_ReservationLinks    *[]*ReservationLink    `protobuf:"bytes,5,rep,name=reservation_links,json=reservationLinks"`
	xxx_hidden_XNoresv             bool                   `protobuf:"varint,6,opt,name=_noresv"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ScheduleGroup) Reset() {
	*x = ScheduleGroup{}
	mi := &file_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleGroup) ProtoMessage() {}

func (x *ScheduleGroup) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScheduleGroup) GetLabel() string {
	if x != nil {
		return x.xxx_hidden_Label
	}
	return ""
}

func (x *ScheduleGroup) GetXTitle() string {
	if x != nil {
		return x.xxx_hidden_XTitle
	}
	return ""
}

func (x *ScheduleGroup) GetScheduleChangesHtml() string {
	if x != nil {
		return x.xxx_hidden_ScheduleChangesHtml
	}
	return ""
}

func (x *ScheduleGroup) GetSchedules() []*Schedule {
	if x != nil {
		if x.xxx_hidden_Schedules != nil {
			return *x.xxx_hidden_Schedules
		}
	}
	return nil
}

func (x *ScheduleGroup) GetReservationLinks() []*ReservationLink {
	if x != nil {
		if x.xxx_hidden_ReservationLinks != nil {
			return *x.xxx_hidden_ReservationLinks
		}
	}
	return nil
}

func (x *ScheduleGroup) GetXNoresv() bool {
	if x != nil {
		return x.xxx_hidden_XNoresv
	}
	return false
}

func (x *ScheduleGroup) SetLabel(v string) {
	x.xxx_hidden_Label = v
}

func (x *ScheduleGroup) SetXTitle(v string) {
	x.xxx_hidden_XTitle = v
}

func (x *ScheduleGroup) SetScheduleChangesHtml(v string) {
	x.xxx_hidden_ScheduleChangesHtml = v
}

func (x *ScheduleGroup) SetSchedules(v []*Schedule) {
	x.xxx_hidden_Schedules = &v
}

func (x *ScheduleGroup) SetReservationLinks(v []*ReservationLink) {
	x.xxx_hidden_ReservationLinks = &v
}

func (x *ScheduleGroup) SetXNoresv(v bool) {
	x.xxx_hidden_XNoresv = v
}

type ScheduleGroup_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Label               string
	XTitle              string
	ScheduleChangesHtml string
	Schedules           []*Schedule
	ReservationLinks    []*ReservationLink
	XNoresv             bool
}

func (b0 ScheduleGroup_builder) Build() *ScheduleGroup {
	m0 := &ScheduleGroup{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Label = b.Label
	x.xxx_hidden_XTitle = b.XTitle
	x.xxx_hidden_ScheduleChangesHtml = b.ScheduleChangesHtml
	x.xxx_hidden_Schedules = &b.Schedules
	x.xxx_hidden_ReservationLinks = &b.ReservationLinks
	x.xxx_hidden_XNoresv = b.XNoresv
	return m0
}

type Schedule struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Caption     string                 `protobuf:"bytes,1,opt,name=caption"`
	xxx_hidden_XName       string                 `protobuf:"bytes,2,opt,name=_name"`
	xxx_hidden_XDate       string                 `protobuf:"bytes,5,opt,name=_date"`
	xxx_hidden_XFrom       int32                  `protobuf:"varint,6,opt,name=_from"`
	xxx_hidden_XTo         int32                  `protobuf:"varint,7,opt,name=_to"`
	xxx_hidden_Days        []string               `protobuf:"bytes,3,rep,name=days"`
	xxx_hidden_XDaydates   []int32                `protobuf:"varint,8,rep,packed,name=_daydates"`
	xxx_hidden_Activities  *[]*Schedule_Activity  `protobuf:"bytes,4,rep,name=activities"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Schedule) GetCaption() string {
	if x != nil {
		return x.xxx_hidden_Caption
	}
	return ""
}

func (x *Schedule) GetXName() string {
	if x != nil {
		return x.xxx_hidden_XName
	}
	return ""
}

func (x *Schedule) GetXDate() string {
	if x != nil {
		return x.xxx_hidden_XDate
	}
	return ""
}

func (x *Schedule) GetXFrom() int32 {
	if x != nil {
		return x.xxx_hidden_XFrom
	}
	return 0
}

func (x *Schedule) GetXTo() int32 {
	if x != nil {
		return x.xxx_hidden_XTo
	}
	return 0
}

func (x *Schedule) GetDays() []string {
	if x != nil {
		return x.xxx_hidden_Days
	}
	return nil
}

func (x *Schedule) GetXDaydates() []int32 {
	if x != nil {
		return x.xxx_hidden_XDaydates
	}
	return nil
}

func (x *Schedule) GetActivities() []*Schedule_Activity {
	if x != nil {
		if x.xxx_hidden_Activities != nil {
			return *x.xxx_hidden_Activities
		}
	}
	return nil
}

func (x *Schedule) SetCaption(v string) {
	x.xxx_hidden_Caption = v
}

func (x *Schedule) SetXName(v string) {
	x.xxx_hidden_XName = v
}

func (x *Schedule) SetXDate(v string) {
	x.xxx_hidden_XDate = v
}

func (x *Schedule) SetXFrom(v int32) {
	x.xxx_hidden_XFrom = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *Schedule) SetXTo(v int32) {
	x.xxx_hidden_XTo = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *Schedule) SetDays(v []string) {
	x.xxx_hidden_Days = v
}

func (x *Schedule) SetXDaydates(v []int32) {
	x.xxx_hidden_XDaydates = v
}

func (x *Schedule) SetActivities(v []*Schedule_Activity) {
	x.xxx_hidden_Activities = &v
}

func (x *Schedule) HasXFrom() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Schedule) HasXTo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Schedule) ClearXFrom() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_XFrom = 0
}

func (x *Schedule) ClearXTo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_XTo = 0
}

type Schedule_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Caption    string
	XName      string
	XDate      string
	XFrom      *int32
	XTo        *int32
	Days       []string
	XDaydates  []int32
	Activities []*Schedule_Activity
}

func (b0 Schedule_builder) Build() *Schedule {
	m0 := &Schedule{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Caption = b.Caption
	x.xxx_hidden_XName = b.XName
	x.xxx_hidden_XDate = b.XDate
	if b.XFrom != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_XFrom = *b.XFrom
	}
	if b.XTo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_XTo = *b.XTo
	}
	x.xxx_hidden_Days = b.Days
	x.xxx_hidden_XDaydates = b.XDaydates
	x.xxx_hidden_Activities = &b.Activities
	return m0
}

type TimeRange struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Label       string                 `protobuf:"bytes,1,opt,name=label"`
	xxx_hidden_XStart      int32                  `protobuf:"varint,2,opt,name=_start"`
	xxx_hidden_XEnd        int32                  `protobuf:"varint,3,opt,name=_end"`
	xxx_hidden_XWkday      Weekday                `protobuf:"varint,4,opt,name=_wkday,enum=ottrec.v1.Weekday"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_schema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TimeRange) GetLabel() string {
	if x != nil {
		return x.xxx_hidden_Label
	}
	return ""
}

func (x *TimeRange) GetXStart() int32 {
	if x != nil {
		return x.xxx_hidden_XStart
	}
	return 0
}

func (x *TimeRange) GetXEnd() int32 {
	if x != nil {
		return x.xxx_hidden_XEnd
	}
	return 0
}

func (x *TimeRange) GetXWkday() Weekday {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_XWkday
		}
	}
	return Weekday_SUNDAY
}

func (x *TimeRange) SetLabel(v string) {
	x.xxx_hidden_Label = v
}

func (x *TimeRange) SetXStart(v int32) {
	x.xxx_hidden_XStart = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *TimeRange) SetXEnd(v int32) {
	x.xxx_hidden_XEnd = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *TimeRange) SetXWkday(v Weekday) {
	x.xxx_hidden_XWkday = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *TimeRange) HasXStart() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TimeRange) HasXEnd() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TimeRange) HasXWkday() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TimeRange) ClearXStart() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_XStart = 0
}

func (x *TimeRange) ClearXEnd() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_XEnd = 0
}

func (x *TimeRange) ClearXWkday() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_XWkday = Weekday_SUNDAY
}

type TimeRange_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Label  string
	XStart *int32
	XEnd   *int32
	XWkday *Weekday
}

func (b0 TimeRange_builder) Build() *TimeRange {
	m0 := &TimeRange{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Label = b.Label
	if b.XStart != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_XStart = *b.XStart
	}
	if b.XEnd != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_XEnd = *b.XEnd
	}
	if b.XWkday != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_XWkday = *b.XWkday
	}
	return m0
}

type ReservationLink struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Label string                 `protobuf:"bytes,1,opt,name=label"`
	xxx_hidden_Url   string                 `protobuf:"bytes,2,opt,name=url"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReservationLink) Reset() {
	*x = ReservationLink{}
	mi := &file_schema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationLink) ProtoMessage() {}

func (x *ReservationLink) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReservationLink) GetLabel() string {
	if x != nil {
		return x.xxx_hidden_Label
	}
	return ""
}

func (x *ReservationLink) GetUrl() string {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return ""
}

func (x *ReservationLink) SetLabel(v string) {
	x.xxx_hidden_Label = v
}

func (x *ReservationLink) SetUrl(v string) {
	x.xxx_hidden_Url = v
}

type ReservationLink_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Label string
	Url   string
}

func (b0 ReservationLink_builder) Build() *ReservationLink {
	m0 := &ReservationLink{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Label = b.Label
	x.xxx_hidden_Url = b.Url
	return m0
}

type Schedule_ActivityDay struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Times *[]*TimeRange          `protobuf:"bytes,1,rep,name=times"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Schedule_ActivityDay) Reset() {
	*x = Schedule_ActivityDay{}
	mi := &file_schema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule_ActivityDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule_ActivityDay) ProtoMessage() {}

func (x *Schedule_ActivityDay) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Schedule_ActivityDay) GetTimes() []*TimeRange {
	if x != nil {
		if x.xxx_hidden_Times != nil {
			return *x.xxx_hidden_Times
		}
	}
	return nil
}

func (x *Schedule_ActivityDay) SetTimes(v []*TimeRange) {
	x.xxx_hidden_Times = &v
}

type Schedule_ActivityDay_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Times []*TimeRange
}

func (b0 Schedule_ActivityDay_builder) Build() *Schedule_ActivityDay {
	m0 := &Schedule_ActivityDay{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Times = &b.Times
	return m0
}

type Schedule_Activity struct {
	state                  protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Label       string                   `protobuf:"bytes,1,opt,name=label"`
	xxx_hidden_XName       string                   `protobuf:"bytes,2,opt,name=_name"`
	xxx_hidden_XResv       bool                     `protobuf:"varint,4,opt,name=_resv"`
	xxx_hidden_Days        *[]*Schedule_ActivityDay `protobuf:"bytes,3,rep,name=days"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Schedule_Activity) Reset() {
	*x = Schedule_Activity{}
	mi := &file_schema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule_Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule_Activity) ProtoMessage() {}

func (x *Schedule_Activity) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Schedule_Activity) GetLabel() string {
	if x != nil {
		return x.xxx_hidden_Label
	}
	return ""
}

func (x *Schedule_Activity) GetXName() string {
	if x != nil {
		return x.xxx_hidden_XName
	}
	return ""
}

func (x *Schedule_Activity) GetXResv() bool {
	if x != nil {
		return x.xxx_hidden_XResv
	}
	return false
}

func (x *Schedule_Activity) GetDays() []*Schedule_ActivityDay {
	if x != nil {
		if x.xxx_hidden_Days != nil {
			return *x.xxx_hidden_Days
		}
	}
	return nil
}

func (x *Schedule_Activity) SetLabel(v string) {
	x.xxx_hidden_Label = v
}

func (x *Schedule_Activity) SetXName(v string) {
	x.xxx_hidden_XName = v
}

func (x *Schedule_Activity) SetXResv(v bool) {
	x.xxx_hidden_XResv = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Schedule_Activity) SetDays(v []*Schedule_ActivityDay) {
	x.xxx_hidden_Days = &v
}

func (x *Schedule_Activity) HasXResv() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Schedule_Activity) ClearXResv() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_XResv = false
}

type Schedule_Activity_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Label string
	XName string
	XResv *bool
	Days  []*Schedule_ActivityDay
}

func (b0 Schedule_Activity_builder) Build() *Schedule_Activity {
	m0 := &Schedule_Activity{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Label = b.Label
	x.xxx_hidden_XName = b.XName
	if b.XResv != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_XResv = *b.XResv
	}
	x.xxx_hidden_Days = &b.Days
	return m0
}

var File_schema_proto protoreflect.FileDescriptor

const file_schema_proto_rawDesc = "" +
	"\n" +
	"\fschema.proto\x12\tottrec.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"]\n" +
	"\x04Data\x123\n" +
	"\n" +
	"facilities\x18\x01 \x03(\v2\x13.ottrec.v1.FacilityR\n" +
	"facilities\x12 \n" +
	"\vattribution\x18\x02 \x03(\tR\vattribution\"\xec\x02\n" +
	"\bFacility\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\vdescription\x18\x02 \x01(\tR\x04desc\x12)\n" +
	"\x06source\x18\x03 \x01(\v2\x11.ottrec.v1.SourceR\x06source\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x122\n" +
	"\a_lnglat\x18\x05 \x01(\v2\x11.ottrec.v1.LngLatB\x05\xaa\x01\x02\b\x01R\a_lnglat\x12-\n" +
	"\x12notifications_html\x18\x06 \x01(\tR\x11notificationsHtml\x12,\n" +
	"\x12special_hours_html\x18\a \x01(\tR\x10specialHoursHtml\x12A\n" +
	"\x0fschedule_groups\x18\b \x03(\v2\x18.ottrec.v1.ScheduleGroupR\x0escheduleGroups\x12\x18\n" +
	"\a_errors\x18\t \x03(\tR\a_errors\"S\n" +
	"\x06Source\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x127\n" +
	"\x05_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x05\xaa\x01\x02\b\x01R\x05_date\",\n" +
	"\x06LngLat\x12\x10\n" +
	"\x03lng\x18\x01 \x01(\x02R\x03lng\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x02R\x03lat\"\x87\x02\n" +
	"\rScheduleGroup\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x16\n" +
	"\x06_title\x18\x02 \x01(\tR\x06_title\x122\n" +
	"\x15schedule_changes_html\x18\x03 \x01(\tR\x13scheduleChangesHtml\x121\n" +
	"\tschedules\x18\x04 \x03(\v2\x13.ottrec.v1.ScheduleR\tschedules\x12G\n" +
	"\x11reservation_links\x18\x05 \x03(\v2\x1a.ottrec.v1.ReservationLinkR\x10reservationLinks\x12\x18\n" +
	"\a_noresv\x18\x06 \x01(\bR\a_noresv\"\xbc\x03\n" +
	"\bSchedule\x12\x18\n" +
	"\acaption\x18\x01 \x01(\tR\acaption\x12\x14\n" +
	"\x05_name\x18\x02 \x01(\tR\x05_name\x12\x14\n" +
	"\x05_date\x18\x05 \x01(\tR\x05_date\x12\x1b\n" +
	"\x05_from\x18\x06 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x05_from\x12\x17\n" +
	"\x03_to\x18\a \x01(\x05B\x05\xaa\x01\x02\b\x01R\x03_to\x12\x12\n" +
	"\x04days\x18\x03 \x03(\tR\x04days\x12\x1c\n" +
	"\t_daydates\x18\b \x03(\x05R\t_daydates\x12<\n" +
	"\n" +
	"activities\x18\x04 \x03(\v2\x1c.ottrec.v1.Schedule.ActivityR\n" +
	"activities\x1a9\n" +
	"\vActivityDay\x12*\n" +
	"\x05times\x18\x01 \x03(\v2\x14.ottrec.v1.TimeRangeR\x05times\x1a\x88\x01\n" +
	"\bActivity\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05_name\x18\x02 \x01(\tR\x05_name\x12\x1b\n" +
	"\x05_resv\x18\x04 \x01(\bB\x05\xaa\x01\x02\b\x01R\x05_resv\x123\n" +
	"\x04days\x18\x03 \x03(\v2\x1f.ottrec.v1.Schedule.ActivityDayR\x04days\"\x8e\x01\n" +
	"\tTimeRange\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1d\n" +
	"\x06_start\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x06_start\x12\x19\n" +
	"\x04_end\x18\x03 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x04_end\x121\n" +
	"\x06_wkday\x18\x04 \x01(\x0e2\x12.ottrec.v1.WeekdayB\x05\xaa\x01\x02\b\x01R\x06_wkday\"9\n" +
	"\x0fReservationLink\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url*k\n" +
	"\aWeekday\x12\n" +
	"\n" +
	"\x06SUNDAY\x10\x00\x12\n" +
	"\n" +
	"\x06MONDAY\x10\x01\x12\v\n" +
	"\aTUESDAY\x10\x02\x12\r\n" +
	"\tWEDNESDAY\x10\x03\x12\f\n" +
	"\bTHURSDAY\x10\x04\x12\n" +
	"\n" +
	"\x06FRIDAY\x10\x05\x12\f\n" +
	"\bSATURDAY\x10\x06\x1a\x04:\x02\x10\x02B\x05\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_schema_proto_goTypes = []any{
	(Weekday)(0),                  // 0: ottrec.v1.Weekday
	(*Data)(nil),                  // 1: ottrec.v1.Data
	(*Facility)(nil),              // 2: ottrec.v1.Facility
	(*Source)(nil),                // 3: ottrec.v1.Source
	(*LngLat)(nil),                // 4: ottrec.v1.LngLat
	(*ScheduleGroup)(nil),         // 5: ottrec.v1.ScheduleGroup
	(*Schedule)(nil),              // 6: ottrec.v1.Schedule
	(*TimeRange)(nil),             // 7: ottrec.v1.TimeRange
	(*ReservationLink)(nil),       // 8: ottrec.v1.ReservationLink
	(*Schedule_ActivityDay)(nil),  // 9: ottrec.v1.Schedule.ActivityDay
	(*Schedule_Activity)(nil),     // 10: ottrec.v1.Schedule.Activity
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_schema_proto_depIdxs = []int32{
	2,  // 0: ottrec.v1.Data.facilities:type_name -> ottrec.v1.Facility
	3,  // 1: ottrec.v1.Facility.source:type_name -> ottrec.v1.Source
	4,  // 2: ottrec.v1.Facility._lnglat:type_name -> ottrec.v1.LngLat
	5,  // 3: ottrec.v1.Facility.schedule_groups:type_name -> ottrec.v1.ScheduleGroup
	11, // 4: ottrec.v1.Source._date:type_name -> google.protobuf.Timestamp
	6,  // 5: ottrec.v1.ScheduleGroup.schedules:type_name -> ottrec.v1.Schedule
	8,  // 6: ottrec.v1.ScheduleGroup.reservation_links:type_name -> ottrec.v1.ReservationLink
	10, // 7: ottrec.v1.Schedule.activities:type_name -> ottrec.v1.Schedule.Activity
	0,  // 8: ottrec.v1.TimeRange._wkday:type_name -> ottrec.v1.Weekday
	7,  // 9: ottrec.v1.Schedule.ActivityDay.times:type_name -> ottrec.v1.TimeRange
	9,  // 10: ottrec.v1.Schedule.Activity.days:type_name -> ottrec.v1.Schedule.ActivityDay
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_schema_proto_init() }
func file_schema_proto_init() {
	if File_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_proto_goTypes,
		DependencyIndexes: file_schema_proto_depIdxs,
		EnumInfos:         file_schema_proto_enumTypes,
		MessageInfos:      file_schema_proto_msgTypes,
	}.Build()
	File_schema_proto = out.File
	file_schema_proto_goTypes = nil
	file_schema_proto_depIdxs = nil
}
