name: CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
    inputs:
      zyte:
        type: boolean
      purge_listing:
        type: boolean
        default: true
      purge_facility:
        type: boolean
        default: true
      purge_geocode:
        type: boolean

concurrency:
  group: cache
  cancel-in-progress: false

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: go test -v ./...

  cache:
    needs: [test]
    name: Update cached pages
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'pgaskin/ottrec' }}
    steps:
      - name: Checkout scraper
        uses: actions/checkout@v6

      - name: Authorize app
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ vars.OTTREC_SCRAPER_APP_ID }}
          private-key: ${{ secrets.OTTREC_SCRAPER_PRIVATE_KEY }}
          repositories: ottrec-data

      - name: Checkout cache
        uses: actions/checkout@v6
        with:
          repository: pgaskin/ottrec-data
          ref: cache
          path: cache
          filter: blob:none
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - run: go run ./scraper -cache cache -geocodio -fetch
          ${{ (inputs.zyte) && '-zyte 150' || '' }}
          ${{ (inputs.purge_listing || github.event_name == 'schedule') && '-cache.purge.listing' || '' }}
          ${{ (inputs.purge_facility || github.event_name == 'schedule') && '-cache.purge.facility' || '' }}
          ${{ (inputs.purge_geocode) && '-cache.purge.geocode' || '' }}
        env:
          ZYTE_APIKEY: ${{ secrets.zyte_apikey }}
          GEOCODIO_APIKEY: ${{ secrets.geocodio_apikey }}
          OTTCA_SCRAPER_SECRET: ${{ secrets.ottca_scraper_secret }}

      - name: Commit cache
        run:
          git -C cache add . && {
            git -C cache diff --cached --quiet ||
            git -C cache -c user.name=dummy -c user.email=dummy commit -m "${{(github.event_name=='schedule'&&'full')||(github.event_name=='workflow_dispatch'&&'manual')||'partial'}} update (${{github.event_name}} ${{github.repository}}@${{github.sha}})" ; }

      - name: Push cache
        run: go run github.com/pgaskin/push-signed-commits@v0.0.2 -C cache pgaskin/ottrec-data cache HEAD@{u}..HEAD
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token || github.token }}

  scrape:
    needs: [test, cache]
    name: Scrape cached pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scraper
        uses: actions/checkout@v6

      - name: Authorize app
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ vars.OTTREC_SCRAPER_APP_ID }}
          private-key: ${{ secrets.OTTREC_SCRAPER_PRIVATE_KEY }}
          repositories: ottrec-data
        if: ${{ github.repository == 'pgaskin/ottrec' }}

      - name: Checkout cache
        uses: actions/checkout@v6
        with:
          repository: pgaskin/ottrec-data
          ref: cache
          path: cache
          filter: blob:none
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - run: git -C cache worktree add ../data v1
      - run: rm -fv data/data.*
      - run: go run ./scraper -cache cache -geocodio -scrape -export.pretty
          -export.proto data/data.proto
          -export.pb data/data.pb
          -export.textpb data/data.textpb
          -export.json data/data.json
          -export.errors errors.txt

      - name: Commit data
        run: |
          git -C data add . && {
            git -C data diff --cached --quiet ||
            git -C data -c user.name=dummy -c user.email=dummy commit -m "update (${{github.event_name}} ${{github.repository}}@${{github.sha}}, $(git -C cache rev-parse HEAD))"$'\n'"$(<errors.txt)" ; }

      - name: Push data
        run: go run github.com/pgaskin/push-signed-commits@v0.0.2 -C data pgaskin/ottrec-data v1 HEAD@{u}..HEAD
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token || github.token }}
        if: ${{ github.repository == 'pgaskin/ottrec' }}
