name: CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
    inputs:
      zyte:
        type: boolean
      purge_listing:
        type: boolean
        default: true
      purge_facility:
        type: boolean
        default: true
      purge_geocode:
        type: boolean

concurrency:
  group: cache
  cancel-in-progress: false

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: go test -v ./...

  cache:
    needs: [test]
    name: Update cached pages
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'pgaskin/ottrec' }}
    steps:
      - name: Checkout scraper
        uses: actions/checkout@v6

      - name: Checkout cache
        uses: actions/checkout@v6
        with:
          repository: pgaskin/ottrec-data
          ref: cache
          path: cache
          filter: blob:none
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - run: go run ./scraper -cache cache -geocodio -fetch
          ${{ (inputs.zyte) && '-zyte 150' || '' }}
          ${{ (inputs.purge_listing || github.event_name == 'schedule') && '-cache.purge.listing' || '' }}
          ${{ (inputs.purge_facility || github.event_name == 'schedule') && '-cache.purge.facility' || '' }}
          ${{ (inputs.purge_geocode) && '-cache.purge.geocode' || '' }}
        env:
          ZYTE_APIKEY: ${{ secrets.zyte_apikey }}
          GEOCODIO_APIKEY: ${{ secrets.geocodio_apikey }}
          OTTCA_SCRAPER_SECRET: ${{ secrets.ottca_scraper_secret }}

      - name: Commit cache
        run: git -C cache add . && go run github.com/pgaskin/push-signed-commits@v0.0.4 -C cache -app ${{ vars.OTTREC_SCRAPER_APP_ID }} -commit pgaskin/ottrec-data cache "${{(github.event_name=='schedule'&&'full')||(github.event_name=='workflow_dispatch'&&'manual')||'partial'}} update (${{github.event_name}} ${{github.repository}}@${{github.sha}})"
        env:
          APP_PRIVATE_KEY: ${{ secrets.OTTREC_SCRAPER_PRIVATE_KEY }}

  scrape:
    needs: [test, cache]
    name: Scrape cached pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scraper
        uses: actions/checkout@v6

      - name: Checkout cache
        uses: actions/checkout@v6
        with:
          repository: pgaskin/ottrec-data
          ref: cache
          path: cache
          filter: blob:none
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - run: git -C cache worktree add ../data v1
      - run: rm -fv data/data.*
      - run: go run ./scraper -cache cache -geocodio -scrape -export.pretty
          -export.proto data/data.proto
          -export.pb data/data.pb
          -export.textpb data/data.textpb
          -export.json data/data.json
          -export.errors errors.txt

      - name: Commit data
        run: git -C data add . && go run github.com/pgaskin/push-signed-commits@v0.0.4 -C data -app ${{ vars.OTTREC_SCRAPER_APP_ID }} -commit pgaskin/ottrec-data data "update (${{github.event_name}} ${{github.repository}}@${{github.sha}}, $(git -C cache rev-parse HEAD))"$'\n'"$(<errors.txt)"
        env:
          APP_PRIVATE_KEY: ${{ secrets.OTTREC_SCRAPER_PRIVATE_KEY }}
        if: ${{ github.repository == 'pgaskin/ottrec' }}
